* Option Pricing Visualization

This is a personal project that I am running to display some important aspects in option pricing. I will eventually want to have plots for
- [x] Sample Paths from Geometric Brownian Motion
- [ ] Pricing Surface for Various Options with Varying Parameters
- [ ] Greeks

** Todos
- [x] Implement Geometric Brownian Motion Class
- [x] Implement Plotting for Geometric Brownian Motion Sample Paths
- [x] Implement European Call Option Class
- [x] Implement Method to Price European Call Options
- [ ] Implement a Generalized Option Class
- [ ] Restructure European Call Option to inherit properties from general Option Class
- [ ] Implement Monte Carlo Methods to price options and not just European Calls or Puts  

** Goals
One of my goals of this project is to get used to writing more object-oriented python code. Most of the python code I have written is mostly with scripting and writing basic functions, and I want to try a more object oriented approach for this project to see where it has its benefits. I am also trying to refresh on some of my knowledge of option pricing from my Stochastic Calculus class and to hopefully get a better understanding of some of the inner workings in modern option pricing.
